version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: tributos-db
    environment:
      POSTGRES_USER: tributos_user
      POSTGRES_PASSWORD: tributos_password
      POSTGRES_DB: tributos_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
